### ISSUE TITLE
Changes in Rwanda forms of the admin interface

### ISSUE THREAD

**Issue by johan-cdh** [CDH-DevTeam/rwanda#14]
After a meeting with the Rwanda project on the 13th of October it was pointed out by Tove and Amini the following suggestions for the Admin interface (the forms).
1) In the form of **Place of interest** there is a _Parent place_ dropdown. It should be expanded to a auto-complete box. Just like it is implemented in the Image forms and the field _Place of interest_.

2) In the place overview there is an initial map where the coordinates are set to the coordinates 0,0 and zoom 0. Would it be possible to zoom in on Kigali where the populated map is visible? The initial setting of zoom level 14 would be a good choice. The WGS 84 coordinates for Kigali is -1.943889, 30.059444

3) In the **Image** overview there is a filter that can filter by _Place of interest_. It should also be a autocomplete box.

4) They also wanted a new table **Document** with the same fields as in the table of **Text** and with the same relations to Authors and Informants. They also wanted an additional field with of _filename_ to keep track of a possible PDF-document for the future.

**Comment by AramKarimi** [comment]
1- I updated  Parent place dropdown to auto-complete box.
2- I couldn't find any config for LeafletAdmin to setup coordinates but I'll check if there is any other solution for this.
3- As you have mentioned in first issue, Place of interest in image model is already auto-complete item.
4- I added document model to database and they can add their document now.
