### ISSUE TITLE
Filter searches

### ISSUE THREAD

**Issue by siskahumlesjo** [CDH-DevTeam/rwanda#20]
The search function doesn't filter but adds more options when you click, for example, English and Buildings. Tove wants an advanced search that filters down. Somehow it needs to show which ones are, for example, FR-KIN AND post-independence.

**Comment by AramKarimi** [comment]
now we have advanced search option and we filter based on different options:
https://diana.dh.gu.se/api/rwanda/advance/search/?source=image&period=&place_type=&language=
source could be image, interviews or document.
