### ISSUE TITLE
URL paths of the main entities in the database

### ISSUE THREAD

**Issue by johan-cdh** [CDH-DevTeam/rwanda#4]
URL paths should reflect the navigation and display of the **main** entities of the database, like
```
https://rwanda.dh.gu.se/place/{identifier},
https://rwanda.dh.gu.se/placename/{identifier},
https://rwanda.dh.gu.se/image/{identifier},
https://rwanda.dh.gu.se/interview/{identifier}
```
This way it will be possible to reference the entities in the database and jump directly to them from outside.
When doing so the map should be centered and possible zoomed to the location of the place or the place associated with the source (i.e. image, interview, place name).

**Comment by kikkipedia** [comment]
Zoom is fixed
