### ISSUE TITLE
Selection of content on the map

### ISSUE THREAD

**Issue by johan-cdh** [CDH-DevTeam/rwanda#5]
Only places that have either a place name, image _or_ an interview should be displayed on the map. Places with a name that **only** has OpenStreetMap (OSM) as informant should be excludes at all times. Selection of the content on the map, that is evidence in different sources,  could be implemented as the advanced search in the interface of SHFA, but here, with multi-select dropdowns.

**Comment by kikkipedia** [comment]
I think we need to flag them in the backend
