### ISSUE TITLE
Search interface

### ISSUE THREAD

**Issue by johan-cdh** [CDH-DevTeam/rwanda#6]
Search interface is already implemented. It needs some fine tuning. The entity Place (Place of interest) has no name attribute. Attested names is an entity of its own and connected to Place. The search interface search among all name attestations.
When clicking on a name in the result list, the map should be zoomed and centered around the place and display basic information about the place itself, Interviews (Texts), Images and Place names related to that place.

**Comment by kikkipedia** [comment]
Place details are showing and zooms in on map
